### ISSUE TITLE
运行zsh run_realsense.zsh出现的问题

### ISSUE THREAD

**Issue by puyiwen** [eugenelyj/Calib_DELTAR#1]
大佬您好，感谢您公布TOF和RGB对齐的代码。我在运行这个代码时发现个问题，我用的是您给的example data数据，ORB_SLAM2也已经编译通过了，但是在运行` zsh run_realsense.zsh`时出现个问题。`找不到/home/puyiwen/Calib_DELTAR/ORB_SLAM2/data/associate.py`这个文件。我查阅了您的代码，确实没发现这个associate.py文件。这个是代码有缺失还是我之前编译的ORB_SLAM2没有生成这个？期待您的回复

**Comment by eugenelyj** [comment]
@puyiwen 不好意思，老的代码忘记删了。现在你重新clone一下再试试？用`git submodule update --init --recursive`拉一下orb的代码

**Comment by puyiwen** [comment]
> @puyiwen 不好意思，老的代码忘记删了。现在你重新clone一下再试试？用`git submodule update --init --recursive`拉一下orb的代码

大佬，我看你的最新代码里面，ORB_SLAM2这块内容给删掉了。那这个ORB_SLAM2是没有必要做的？还是我要在ORB_SLAM2官方包里把这个运行一下？

**Comment by puyiwen** [comment]
> > @puyiwen 不好意思，老的代码忘记删了。现在你重新clone一下再试试？用`git submodule update --init --recursive`拉一下orb的代码
> 
> 大佬，我看你的最新代码里面，ORB_SLAM2这块内容给删掉了。那这个ORB_SLAM2是没有必要做的？还是我要在ORB_SLAM2官方包里把这个运行一下？

大佬，我这边跑通了你readme里面的最后一步step 5, 我看到pt2plane.cpp文件是计算了TOF和RGB的外参？外参是calib_rot、calib_t还是pt2pt_rot、pt2pt_t？这个文件最后得到的是什么。。还有一个问题，TOF的时间戳如何和RGB的对齐？

**Comment by eugenelyj** [comment]
@puyiwen Hi，为了方便版本控制，我把orb的代码挪到[这里](https://github.com/eugenelyj/ORB_SLAM2_DELTAR)了，这样可以看到我的修改。你在这个项目的根目录下用上面那个git submodule的命令（readme里应该也有写）就能把这个代码拉下来了。

**Comment by eugenelyj** [comment]
@puyiwen 这个文件最后得到的就是ToF和RGB的外参。calib_rot、calib_t和pt2pl_rot、pt2pl_t是一样的，这里代码写的有点迷惑了，我晚点再提交一版更新下。
