### ISSUE TITLE
L5 TOF内参

### ISSUE THREAD

**Issue by puyiwen** [eugenelyj/Calib_DELTAR#2]
您好，您能给一个L5的内参吗？

**Comment by puyiwen** [comment]
emm，我还有一些问题想请教您
1.您给的标定demo图片大概是有1000张，这些图片做标定数量是不是有点多？还是说数量多，标定效果越好？
2.需要三个不平行的平面进行标定，可以只用两个平面吗？还是说必须得用三个不平行的平面？
3.您给的demo数据里的tof数据，N 43 和 Status:5 这两个参数代表什么？
期待您的回复

**Comment by eugenelyj** [comment]
Hi，那个内参是根据官网文档给出的FoV算的。另外三个问题:
1. 因为我们录制数据的时候就采了这么多图像，然后理论上解那个外参矩阵的时候约束冗余一些是更好的，所以就都用上了。也没有测试过稀疏采样，只有几十张或者别的数量的效果。
2. 因为外参矩阵自由度的关系，应该是要三个不平行面才行的。
3. 这个状态是ToF直接返回的，他有很多文档的，其中就有介绍这个值的含义。您要是找不到的话，回头我找找发下链接。

**Comment by puyiwen** [comment]
> Hi，那个内参是根据官网文档给出的FoV算的。另外三个问题:
> 
> 1. 因为我们录制数据的时候就采了这么多图像，然后理论上解那个外参矩阵的时候约束冗余一些是更好的，所以就都用上了。也没有测试过稀疏采样，只有几十张或者别的数量的效果。
> 2. 因为外参矩阵自由度的关系，应该是要三个不平行面才行的。
> 3. 这个状态是ToF直接返回的，他有很多文档的，其中就有介绍这个值的含义。您要是找不到的话，回头我找找发下链接。

谢谢您的回复，我这边tof输出的格式和你输出来的不一样。。您能给我一个TOF返回数值详细介绍的链接吗？还有一问题，您用了哪些方法能保证tof和realsense得到的数据是同步的呢？我发现tof数据总共910个，您的rgb和depth为1100多张

**Comment by puyiwen** [comment]
emm，我运行代码，到Step3这个步骤有点疑惑，是直接从记录的RGB数据中人眼挑出来只属于一个平面的起始时间戳吗？您给的demo中的plane_order.txt的第一行的2号平面的起始时间戳之前还有一些图片人眼看也是一个平面的，我不清楚为什么要从这个时间戳开始记为2号平面的起始时间戳？还有就是分割平面时间戳的顺序要与Catogoried_MapPoint.txt匹配，这句话要怎么理解，Catogoried_MapPoint.txt中只生成了点云信息，这个地方应该怎么做匹配呢？

**Comment by puyiwen** [comment]
还有一个问题。。我跑了两遍您给的demo数据，参数代码都没有改过，发现每次计算的R和T差别挺大的。我自己的数据我也跑了，也有这个问题。这个问题应该怎么解决？

**Comment by eugenelyj** [comment]
@puyiwen 抱歉回复晚了
"您能给我一个TOF返回数值详细介绍的链接吗": 你方便给一个你的邮箱地址码?我把我下载的文档发你，网站链接我不记得了。
"您用了哪些方法能保证tof和realsense得到的数据是同步的呢": 我们没有做硬件同步，只是先联网确定时间戳一致后，各录各的，然后用最近邻方式做了软同步。
"Step3这个步骤有点疑惑": 这个数据时间戳和下标标注是另一个同学做的，我没印象了。有可能没标的太精细存在一些误差。具体理解建议结合代码来看。简单地说就是2个传感器看到的平面能对应起来就好了。
"我跑了两遍您给的demo数据，参数代码都没有改过，发现每次计算的R和T差别挺大的"：这个好像没遇到过，方便说下具体差别多大吗?

**Comment by puyiwen** [comment]
> @puyiwen 抱歉回复晚了 "您能给我一个TOF返回数值详细介绍的链接吗": 你方便给一个你的邮箱地址码?我把我下载的文档发你，网站链接我不记得了。 "您用了哪些方法能保证tof和realsense得到的数据是同步的呢": 我们没有做硬件同步，只是先联网确定时间戳一致后，各录各的，然后用最近邻方式做了软同步。 "Step3这个步骤有点疑惑": 这个数据时间戳和下标标注是另一个同学做的，我没印象了。有可能没标的太精细存在一些误差。具体理解建议结合代码来看。简单地说就是2个传感器看到的平面能对应起来就好了。 "我跑了两遍您给的demo数据，参数代码都没有改过，发现每次计算的R和T差别挺大的"：这个好像没遇到过，方便说下具体差别多大吗?

谢谢您的回复，我之前问的一些问题，目前已经都解决了。。现在我比较疑惑，已知TOF和RGB的外参，将tof投影到RGB上的时候，我只能将8x8 64个点投影上去，不像您论文中展示的，会呈现出一块矩形。您能给个TOF投影到RGB上的代码吗？我的邮箱地址：291931809@qq.com。再次感谢您。

**Comment by eugenelyj** [comment]
好的，我把文档都发过去了。
另外，投影的话我就是把一整个L5的区域当成同一个深度，简单的说，就是把四个角点赋值成测量的深度，然后warp过去的，所以就是一块像方形的区域。准确的说，其实不是方形的。

**Comment by zhaojinkui** [comment]
很棒的工作，能将TOF投影到RGB上的代码也发我一份么？感激不尽。 邮箱地址是294486415@qq.com
